version: "3"
services:
  app: 
    build: .
    depends_on:
      - postgres
    ports: 
      - ${PORT}:${PORT}
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; npm start'
    depends_on:
      - db
    networks: 
      - webnet
    environment:
      - DATABASE_URL=postgres://${DB_USERNAME}:${DB_PASSWORD}@host.docker.internal:5432/${DB_NAME}
      - PORT=${PORT}
  db:
    image: postgres
    restart: unless-stopped
    networks: 
      - webnet
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
networks:
  webnet: